/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package apk.perpustakaan;

import java.awt.*;
import javax.swing.table.DefaultTableModel;
import com.toedter.calendar.JDateChooser;

public class tambahtransaksi extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(tambahtransaksi.class.getName());

    /**
     * Creates new form tambahtransaksi
     */
    public tambahtransaksi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idtransaksi = new javax.swing.JTextField();
        npeminjam = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        combobuku = new javax.swing.JComboBox<>();
        tglpinjam = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tglkembali = new com.toedter.calendar.JDateChooser();
        tdenda = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tcatatan = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        roundedButton22 = new apk.perpustakaan.RoundedButton2();
        roundedButton21 = new apk.perpustakaan.RoundedButton2();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(500, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 10));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ahmad Faisal\\Documents\\NetBeansProjects\\perpustakaan_netbeans\\src\\main\\Resources\\Assets\\file-text.png")); // NOI18N
        jLabel1.setText("Tambah Transaksi");
        jPanel2.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        jPanel3.setPreferredSize(new java.awt.Dimension(375, 450));
        jPanel3.setLayout(new java.awt.GridLayout(8, 2, 20, 30));

        jLabel2.setText("ID Transaksi");
        jPanel3.add(jLabel2);

        jLabel4.setText("Peminjam");
        jPanel3.add(jLabel4);

        idtransaksi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idtransaksi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        idtransaksi.addActionListener(this::idtransaksiActionPerformed);
        jPanel3.add(idtransaksi);

        npeminjam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        npeminjam.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        npeminjam.addActionListener(this::npeminjamActionPerformed);
        jPanel3.add(npeminjam);

        jLabel5.setText("Pilih Buku");
        jPanel3.add(jLabel5);

        jLabel6.setText("Tanggal Pinjam");
        jPanel3.add(jLabel6);

        combobuku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laskar Pelangi", "Negeri 5 Menara", "Bumi Manusia", "Ayah" }));
        combobuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(combobuku);

        tglpinjam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(tglpinjam);

        jLabel7.setText("Tanggal Kembali(Jatuh Tempo)");
        jPanel3.add(jLabel7);

        jLabel8.setText("Denda Per hari (Rp)");
        jPanel3.add(jLabel8);

        tglkembali.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(tglkembali);

        tdenda.setBackground(new java.awt.Color(255, 255, 255));
        tdenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tdenda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tdenda.setName(""); // NOI18N
        tdenda.addActionListener(this::tdendaActionPerformed);
        jPanel3.add(tdenda);
        tdenda.getAccessibleContext().setAccessibleDescription("Rp.");

        jLabel9.setText("Catatan");
        jPanel3.add(jLabel9);
        jPanel3.add(jLabel10);

        tcatatan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tcatatan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(tcatatan);

        jPanel4.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 10, 10, 15));

        roundedButton22.setText("Simpan Transaksi");
        roundedButton22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        roundedButton22.setPreferredSize(new java.awt.Dimension(145, 30));
        roundedButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roundedButton22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roundedButton22MouseExited(evt);
            }
        });
        roundedButton22.addActionListener(this::roundedButton22ActionPerformed);
        jPanel5.add(roundedButton22);

        roundedButton21.setBackground(new java.awt.Color(255, 255, 255));
        roundedButton21.setForeground(new java.awt.Color(0, 0, 0));
        roundedButton21.setText("Clear");
        roundedButton21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        roundedButton21.setPreferredSize(new java.awt.Dimension(90, 30));
        roundedButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roundedButton21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roundedButton21MouseExited(evt);
            }
        });
        roundedButton21.addActionListener(this::roundedButton21ActionPerformed);
        jPanel5.add(roundedButton21);

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idtransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtransaksiActionPerformed

    private void npeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npeminjamActionPerformed

    private void roundedButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButton22ActionPerformed
           java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd MMM yyyy");
    String id = idtransaksi.getText();
    String peminjam = npeminjam.getText();
    String buku = combobuku.getSelectedItem().toString();
    String denda = tdenda.getText();
    String catatan = tcatatan.getText();

    // 3. Ambil dan validasi tanggal dari JDateChooser
    if (tglpinjam.getDate() == null || tglkembali.getDate() == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Mohon lengkapi semua tanggal!");
        return;
    }
    String tPinjam = sdf.format(tglpinjam.getDate());
    String tKembali = sdf.format(tglkembali.getDate());

    // 4. Proses masukkan ke JTable di Dashboard
    try {
        // Kita panggil Dashboard (Parent)
        Dashboard dash = (Dashboard) getParent();
        DefaultTableModel model = (DefaultTableModel) dash.tabletransaksi.getModel();

        // Tambah baris (Sesuaikan urutan kolom tabel kamu)
        model.addRow(new Object[]{
            model.getRowCount() + 1, 
            id,          
            peminjam,
            buku,
            tPinjam,
            tKembali,                                                                           
            "Rp. "+denda,                 
            catatan,  
            "Dipinjam",   
        });

        javax.swing.JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan!");
        this.dispose(); // Menutup dialog setelah simpan sukses

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengirim data: " + e.getMessage());
        e.printStackTrace();
    }
    
    }//GEN-LAST:event_roundedButton22ActionPerformed

    private void tdendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdendaActionPerformed
        
    }//GEN-LAST:event_tdendaActionPerformed

    private void roundedButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButton21ActionPerformed
        idtransaksi.setText("");
    npeminjam.setText("");
    tdenda.setText("Rp. ");
    tcatatan.setText("");
    combobuku.setSelectedIndex(0);
    tglpinjam.setDate(null);
    tglkembali.setDate(null);
    idtransaksi.requestFocus();
    }//GEN-LAST:event_roundedButton21ActionPerformed

    private void roundedButton22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedButton22MouseEntered
       roundedButton22.setBackground(new Color(0, 80, 200));
    }//GEN-LAST:event_roundedButton22MouseEntered

    private void roundedButton22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedButton22MouseExited
        roundedButton22.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_roundedButton22MouseExited

    private void roundedButton21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedButton21MouseEntered
        
        roundedButton21.setBackground(new Color(0, 80, 200));
        roundedButton21.setForeground(Color.WHITE);
    }//GEN-LAST:event_roundedButton21MouseEntered

    private void roundedButton21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedButton21MouseExited

        roundedButton21.setBackground(Color.white);
        roundedButton21.setForeground(Color.black);
    }//GEN-LAST:event_roundedButton21MouseExited

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                tambahtransaksi dialog = new tambahtransaksi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combobuku;
    private javax.swing.JTextField idtransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField npeminjam;
    private apk.perpustakaan.RoundedButton2 roundedButton21;
    private apk.perpustakaan.RoundedButton2 roundedButton22;
    private javax.swing.JTextField tcatatan;
    private javax.swing.JTextField tdenda;
    private com.toedter.calendar.JDateChooser tglkembali;
    private com.toedter.calendar.JDateChooser tglpinjam;
    // End of variables declaration//GEN-END:variables
}
